import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/admin/Header";
import Sidebar from "@/components/admin/Sidebar";
import { ToastContainer} from 'react-toastify';


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Admin",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ToastContainer/>
                <Header />
                <div className="grid grid-cols-5">
                    <Sidebar />
                    {children}
                </div>
            </body>
        </html>
    );
}
